// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package sessions

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// PickerDialog is the command palette's modal <dialog> as a choice picker,
// bound to the picker() state a design page composes: a filter (a combobox
// over the listbox, with the active option as its aria-activedescendant), the
// matching choices, and a line when nothing matches. ↑/↓ move, Enter picks,
// Esc closes (the dialog's own cancel), and focus returns to the opener.
func PickerDialog(placeholder string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<dialog class=\"[ palette ]\" x-ref=\"picker\" x-bind:aria-label=\"pickerLabel\" x-on:close=\"pickerClosed\"><input x-ref=\"pickerInput\" type=\"text\" role=\"combobox\" aria-expanded=\"true\" aria-controls=\"picker-results\" aria-autocomplete=\"list\" autocomplete=\"off\" placeholder=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(placeholder)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `sessions/picker.templ`, Line: 18, Col: 28}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" x-bind:aria-label=\"pickerLabel\" x-bind:aria-activedescendant=\"pickerActiveDomId\" x-model=\"pickerQuery\" x-on:input=\"pickerFiltered\" x-on:keydown.down.prevent=\"pickerNext\" x-on:keydown.up.prevent=\"pickerPrevious\" x-on:keydown.enter.prevent=\"pickerChoose\"><div class=\"[ results ]\" id=\"picker-results\" role=\"listbox\" x-bind:aria-label=\"pickerLabel\"><template x-for=\"choice in pickerResults\" x-bind:key=\"choice.id\"><div role=\"option\" x-bind:id=\"choice.domId\" x-bind:aria-selected=\"choice.active\" x-on:click=\"pick(choice.id)\"><span x-text=\"choice.label\"></span><template x-if=\"choice.detail\"><span class=\"[ color-ink-faint text-sm ]\" x-text=\"choice.detail\"></span></template></div></template><template x-if=\"pickerIsEmpty\"><p class=\"[ pad-s color-ink-faint ]\" data-picker-empty x-text=\"pickerEmptyText\"></p></template></div></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
