// Command designtokens generates the token layer of the CUBE CSS design system
// from design-system/tokens.json:
//
//	design-system/css/global/tokens.css     custom properties, both themes
//	design-system/css/utilities/tokens.css  design-token utilities (.color-*, .bg-*, …)
//
// Usage, from the repository root:
//
//	go run ./cmd/designtokens          write both files
//	go run ./cmd/designtokens -check   exit 1 if either is stale
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

const header = "/* Generated by `go run ./cmd/designtokens` from tokens.json. Do not edit. */\n"

// scales are the theme-independent token groups, in output order.
var scales = []string{"font", "text", "leading", "weight", "space", "size", "radius", "border", "ease", "duration", "z"}

func main() {
	dir := flag.String("dir", "design-system", "design system directory")
	check := flag.Bool("check", false, "report stale generated files instead of writing them")
	flag.Parse()

	if err := run(*dir, *check); err != nil {
		fmt.Fprintln(os.Stderr, "designtokens:", err)
		os.Exit(1)
	}
}

func run(dir string, check bool) error {
	raw, err := os.ReadFile(filepath.Join(dir, "tokens.json"))
	if err != nil {
		return err
	}
	tokens, err := parse(raw)
	if err != nil {
		return fmt.Errorf("tokens.json: %w", err)
	}
	outputs, err := generate(tokens)
	if err != nil {
		return err
	}

	stale := false
	for _, out := range outputs {
		path := filepath.Join(dir, out.path)
		if check {
			current, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(current, []byte(out.content)) {
				fmt.Fprintln(os.Stderr, "stale:", path)
				stale = true
			}
			continue
		}
		if err := os.WriteFile(path, []byte(out.content), 0o644); err != nil {
			return err
		}
		fmt.Println("wrote", path)
	}
	if stale {
		return errors.New("generated files are stale; run: go run ./cmd/designtokens")
	}
	return nil
}

type output struct{ path, content string }

func generate(tokens object) ([]output, error) {
	vars, err := tokensCSS(tokens)
	if err != nil {
		return nil, err
	}
	utils, err := utilitiesCSS(tokens)
	if err != nil {
		return nil, err
	}
	return []output{
		{"css/global/tokens.css", vars},
		{"css/utilities/tokens.css", utils},
	}, nil
}

func tokensCSS(tokens object) (string, error) {
	var groups []string
	for _, name := range scales {
		g, ok := tokens.object(name)
		if !ok {
			return "", fmt.Errorf("missing token group %q", name)
		}
		groups = append(groups, decls(name, g, "    "))
	}
	themes, _ := tokens.object("themes")
	light, okL := themes.object("light")
	dark, okD := themes.object("dark")
	if !okL || !okD {
		return "", errors.New("themes.light and themes.dark are required")
	}

	var b strings.Builder
	b.WriteString(header + "\n@layer global {\n  :root {\n")
	b.WriteString(strings.Join(groups, "\n\n"))
	b.WriteString("\n\n    color-scheme: light dark;\n  }\n\n  :root {\n")
	b.WriteString(themeDecls(light, "    "))
	b.WriteString("\n  }\n\n  @media (prefers-color-scheme: dark) {\n    :root:not([data-theme=\"light\"]) {\n")
	b.WriteString(themeDecls(dark, "      "))
	b.WriteString("\n    }\n  }\n\n  :root[data-theme=\"dark\"] {\n")
	b.WriteString(themeDecls(dark, "    "))
	b.WriteString("\n  }\n\n  :root[data-theme=\"light\"] { color-scheme: light; }\n  :root[data-theme=\"dark\"] { color-scheme: dark; }\n}\n")
	return b.String(), nil
}

func utilitiesCSS(tokens object) (string, error) {
	list, _ := tokens.get("utilities")
	utilities, ok := list.([]any)
	if !ok {
		return "", errors.New("utilities must be an array")
	}
	light := tokens.mustObject("themes").mustObject("light")

	var blocks []string
	for _, u := range utilities {
		spec, ok := u.(object)
		if !ok {
			return "", errors.New("each utility must be an object")
		}
		prefix, property, group := spec.str("prefix"), spec.str("property"), spec.str("group")
		source, ok := tokens.object(group)
		if !ok {
			source, ok = light.object(group)
		}
		if !ok {
			return "", fmt.Errorf("utility %q: unknown token group %q", prefix, group)
		}
		keys := source.keys()
		if only, ok := spec.get("only"); ok {
			keys = nil
			for _, k := range only.([]any) {
				keys = append(keys, k.(string))
			}
		}
		var lines []string
		for _, key := range keys {
			if _, ok := source.get(key); !ok {
				return "", fmt.Errorf("utility %q: no token %s.%s", prefix, group, key)
			}
			lines = append(lines, fmt.Sprintf("  .%s-%s { %s: var(--%s-%s); }", prefix, key, property, group, key))
		}
		blocks = append(blocks, strings.Join(lines, "\n"))
	}
	return header + "\n@layer utilities {\n" + strings.Join(blocks, "\n\n") + "\n}\n", nil
}

func decls(prefix string, g object, indent string) string {
	lines := make([]string, 0, len(g))
	for _, f := range g {
		lines = append(lines, fmt.Sprintf("%s--%s-%s: %v;", indent, prefix, f.key, f.value))
	}
	return strings.Join(lines, "\n")
}

func themeDecls(theme object, indent string) string {
	parts := make([]string, 0, len(theme))
	for _, f := range theme {
		g, _ := f.value.(object)
		parts = append(parts, decls(f.key, g, indent))
	}
	return strings.Join(parts, "\n")
}

// object is a JSON object that keeps its keys in source order: the order of
// tokens.json is the order of the generated CSS.
type object []field

type field struct {
	key   string
	value any // string, object or []any
}

func (o object) get(key string) (any, bool) {
	for _, f := range o {
		if f.key == key {
			return f.value, true
		}
	}
	return nil, false
}

func (o object) object(key string) (object, bool) {
	v, _ := o.get(key)
	obj, ok := v.(object)
	return obj, ok
}

func (o object) mustObject(key string) object {
	obj, _ := o.object(key)
	return obj
}

func (o object) str(key string) string {
	v, _ := o.get(key)
	s, _ := v.(string)
	return s
}

func (o object) keys() []string {
	keys := make([]string, 0, len(o))
	for _, f := range o {
		keys = append(keys, f.key)
	}
	return keys
}

func parse(raw []byte) (object, error) {
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.UseNumber()
	v, err := value(dec)
	if err != nil {
		return nil, err
	}
	obj, ok := v.(object)
	if !ok {
		return nil, errors.New("top level must be an object")
	}
	return obj, nil
}

func value(dec *json.Decoder) (any, error) {
	tok, err := dec.Token()
	if err != nil {
		return nil, err
	}
	switch t := tok.(type) {
	case json.Delim:
		switch t {
		case '{':
			var obj object
			for dec.More() {
				k, err := dec.Token()
				if err != nil {
					return nil, err
				}
				v, err := value(dec)
				if err != nil {
					return nil, err
				}
				obj = append(obj, field{k.(string), v})
			}
			_, err := dec.Token() // '}'
			return obj, err
		case '[':
			var arr []any
			for dec.More() {
				v, err := value(dec)
				if err != nil {
					return nil, err
				}
				arr = append(arr, v)
			}
			_, err := dec.Token() // ']'
			return arr, err
		}
	case string:
		return t, nil
	case json.Number:
		return t.String(), nil
	case bool, nil:
		return t, nil
	}
	return nil, io.ErrUnexpectedEOF
}
